language: node_js
node_js:
- '5.1'
addons:
  firefox: "43.0"
install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- tar -xjf /tmp/firefox-43.0.tar.bz2 --directory /tmp
- export PATH="/tmp/firefox:$PATH"
- npm config set registry http://registry.npmjs.org/
- npm install
script:
- npm run build:test
deploy:
  skip_cleanup: true
  provider: npm
  on: 
    tags: true
  email : infrastructure@openmrs.org
  api_key:
    secure: $NPM_API_KEY
